***Feature Selection using Statistical Understanding<br>
Context: Not all features improve model performance.<br>
Dataset: Iris***

**Compute correlation matrix**

In [7]:
import numpy as np
import seaborn as sns

iris_df = sns.load_dataset('iris')
iris_df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [8]:
iris_df['species'].value_counts()

species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

In [9]:
#iris_df['species'] = iris_df['species'].map({'setosa': 0,'versicolor':1,'virginica': 2})
#iris_df

In [12]:
correlation_mat = iris_df.corr(numeric_only=True)
correlation_mat

              sepal_length  sepal_width  petal_length  petal_width
sepal_length      1.000000    -0.117570      0.871754     0.817941
sepal_width      -0.117570     1.000000     -0.428440    -0.366126
petal_length      0.871754    -0.428440      1.000000     0.962865
petal_width       0.817941    -0.366126      0.962865     1.000000

**Identify highly correlated features**

In [13]:
correlation_mat.shape

(4, 4)

In [31]:
upper_triu = correlation_mat.where(np.triu(np.ones(correlation_mat.shape), k=1).astype(bool))
high_corr_pairs = upper_triu.stack()
high_corr_pairs = high_corr_pairs[high_corr_pairs.abs() > 0.8].sort_values(ascending=False)
high_corr_pairs

petal_length  petal_width     0.962865
sepal_length  petal_length    0.871754
              petal_width     0.817941
dtype: float64

**Drop redundant features**

In [43]:
to_drop = []
correlation_mat = iris_df.corr(numeric_only = True).abs()
upper_triu = correlation_mat.where(np.triu(np.ones(correlation_mat.shape), k=1).astype(bool))

for column in upper_triu.columns:
    if any(upper_triu[column] > 0.85):
        to_drop.append(column)

print(to_drop)
iris_df.drop(columns=to_drop, inplace=True)
iris_df

['sepal_width', 'petal_length', 'petal_width']

              sepal_length
sepal_length      1.000000
sepal_width       0.117570
petal_length      0.871754
petal_width       0.817941

**Explain: Impact on overfitting and model performance**
***Need to check on this**